name: 'GitHub to Clubhouse'
description: 'Close the GitHub issue and post it to Clubhouse'
inputs:
  github-repo-token:
    description: 'Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
    required: true
  clubhouse-token:
    description: 'Token to use Clubhouse API'
  clubhouse-project-id:
    description: 'The ID of the project whose issue will be made in Clubhouse'
runs:
  using: 'node12'
  main: 'index.js'

